/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module decToBin_13 (
    input [15:0] dgt,
    output reg [15:0] biny
  );
  
  
  
  always @* begin
    biny = 16'h0000;
    
    case (dgt[12+3-:4])
      1'h0: begin
        biny[12+3-:4] = 4'h0;
      end
      1'h1: begin
        biny[12+3-:4] = 4'h1;
      end
      2'h2: begin
        biny[12+3-:4] = 4'h2;
      end
      2'h3: begin
        biny[12+3-:4] = 4'h3;
      end
      3'h4: begin
        biny[12+3-:4] = 4'h4;
      end
      3'h5: begin
        biny[12+3-:4] = 4'h5;
      end
      3'h6: begin
        biny[12+3-:4] = 4'h6;
      end
      3'h7: begin
        biny[12+3-:4] = 4'h7;
      end
      4'h8: begin
        biny[12+3-:4] = 4'h8;
      end
      4'h9: begin
        biny[12+3-:4] = 4'h9;
      end
    endcase
    
    case (dgt[8+3-:4])
      1'h0: begin
        biny[8+3-:4] = 4'h0;
      end
      1'h1: begin
        biny[8+3-:4] = 4'h1;
      end
      2'h2: begin
        biny[8+3-:4] = 4'h2;
      end
      2'h3: begin
        biny[8+3-:4] = 4'h3;
      end
      3'h4: begin
        biny[8+3-:4] = 4'h4;
      end
      3'h5: begin
        biny[8+3-:4] = 4'h5;
      end
      3'h6: begin
        biny[8+3-:4] = 4'h6;
      end
      3'h7: begin
        biny[8+3-:4] = 4'h7;
      end
      4'h8: begin
        biny[8+3-:4] = 4'h8;
      end
      4'h9: begin
        biny[8+3-:4] = 4'h9;
      end
    endcase
    
    case (dgt[4+3-:4])
      1'h0: begin
        biny[4+3-:4] = 4'h0;
      end
      1'h1: begin
        biny[4+3-:4] = 4'h1;
      end
      2'h2: begin
        biny[4+3-:4] = 4'h2;
      end
      2'h3: begin
        biny[4+3-:4] = 4'h3;
      end
      3'h4: begin
        biny[4+3-:4] = 4'h4;
      end
      3'h5: begin
        biny[4+3-:4] = 4'h5;
      end
      3'h6: begin
        biny[4+3-:4] = 4'h6;
      end
      3'h7: begin
        biny[4+3-:4] = 4'h7;
      end
      4'h8: begin
        biny[4+3-:4] = 4'h8;
      end
      4'h9: begin
        biny[4+3-:4] = 4'h9;
      end
    endcase
    
    case (dgt[0+3-:4])
      1'h0: begin
        biny[0+3-:4] = 4'h0;
      end
      1'h1: begin
        biny[0+3-:4] = 4'h1;
      end
      2'h2: begin
        biny[0+3-:4] = 4'h2;
      end
      2'h3: begin
        biny[0+3-:4] = 4'h3;
      end
      3'h4: begin
        biny[0+3-:4] = 4'h4;
      end
      3'h5: begin
        biny[0+3-:4] = 4'h5;
      end
      3'h6: begin
        biny[0+3-:4] = 4'h6;
      end
      3'h7: begin
        biny[0+3-:4] = 4'h7;
      end
      4'h8: begin
        biny[0+3-:4] = 4'h8;
      end
      4'h9: begin
        biny[0+3-:4] = 4'h9;
      end
    endcase
  end
endmodule
