/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module numbergen_3 (
    input clk,
    input rst,
    output reg [11:0] four
  );
  
  
  
  wire [32-1:0] M_pn_gen1_num;
  reg [1-1:0] M_pn_gen1_next;
  reg [32-1:0] M_pn_gen1_seed;
  pn_gen_50 pn_gen1 (
    .clk(clk),
    .rst(rst),
    .next(M_pn_gen1_next),
    .seed(M_pn_gen1_seed),
    .num(M_pn_gen1_num)
  );
  
  reg [31:0] M_seed1_d, M_seed1_q = 1'h0;
  
  always @* begin
    M_seed1_d = M_seed1_q;
    
    M_pn_gen1_seed = M_seed1_q;
    M_pn_gen1_next = 1'h0;
    if (rst) begin
      M_seed1_d = M_seed1_q + 1'h1;
    end
    four = {M_pn_gen1_num[0+2-:3], M_pn_gen1_num[3+2-:3], M_pn_gen1_num[6+2-:3], M_pn_gen1_num[9+2-:3]};
  end
  
  always @(posedge clk) begin
    M_seed1_q <= M_seed1_d;
  end
  
endmodule
